apiVersion: batch/v1
kind: CronJob
metadata:
  name: plus
# lol, 3 spec
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: ubuntu
            image: ubuntu
            command: ['expr', '3', '+', '2']
          restartPolicy: OnFailure