# WRONG!!! There's no connection between a PersistentVolumeClaim and a PersistentVolume in the settings file.
# Because the system will try to find the best match for the two.

# Well kinda, we can connect them by using PVC's spec.volumeName.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
