apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
# this one does not support dynamic provisioning.
# so we'll have to create a persistentVolume manually if we want to use this one.
# https://uklabs.kodekloud.com/topic/storage-class-2/
# if we want it to provision stuff automatically, it has to have some other values.
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
