apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext:
    runAsUser: 1000   # the userID for the pod
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: ubuntu
    image: ubuntu
    ports:
    - containerPort: 8080
    command: ["sleep", "3600"]
    # we can specify the settings for the containers here!
    # This will overwrite the rule above.
    # securityContext:
    #   runAsUser: 1000   # the userID for the pod
    #   runAsGroup: 3000
    #   fsGroup: 2000
    #   # Only containers can have this! Pods don't have this luxury.
    #   capabilities:
    #     drop: ["all"]
    #     add: [ ]


