apiVersion: apps/v1
kind: Deployment
metadata:
  name: otherapp-deployment
  labels:
    app: otherapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: otherapp-pod
      labels:
        app: otherapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        # image: nginx
        image: nginx:1.7.1
  selector:
    matchLabels:
      type: front-end