apiVersion: v1
kind: Service
metadata:
  name: otherapp-service
spec:
  type: NodePort # default is ClusterIP, not this BS.
  ports:
    - port: 80 # only this is mandatory
      targetPort: 80 # if not specified, this will be the same as port
      nodePort: 30004 # if not specified, this will be automatically allocated between 30000 and 32767.
  # selector will connect the service to the pod, this one doesn't have matchLabels
  # instead, we just ctrl c ctrl v the labels of the pod
  # NOTE: To expose the deployment, we use the labels of the pods in the deployments,
  # not the labels of the deployements.
  selector:
    type: front-end
