apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80 # there's no need to specify nodePort for this one?
  selector:
    app: otherapp
    type: back-end