kind: Service
apiVersion: v1
metadata:
  name: db # this is very important!!! Otherwise we can't performing linking, as it's hardcode in the code
  labels:
    name: postgres-service
    app: demo-app
spec:
  selector:
    name: postgres-pod
    app: demo-app
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432