kind: Service
apiVersion: v1
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: demo-app
spec:
  selector:
    name: result-app-pod
    app: demo-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005