apiVersion: v1
kind: Config

clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: fake-ca-file
    server: https://1.2.3.4

users:
- name: my-kube-admin
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: experimenter

contexts:
- name: my-kube-admin@my-kube-playground
  context:
    # namespace: cosmos
    cluster: my-kube-playground
    user: my-kube-admin

  
