apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort # default is ClusterIP, not this BS.
  ports:
    - port: 80 # only this is mandatory
      targetPort: 80 # if not specified, this will be the same as port
      nodePort: 30004 # if not specified, this will be automatically allocated between 30000 and 32767.
  # selector will connect the service to the pod, this one doesn't have matchLabels
  # instead, we just ctrl c ctrl v the labels of the pod
  selector:
    # version: v1 # used to be this before the update.
    version: v2
