apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otherapp-replicaset-2
  labels:
    app: otherapp
spec:
  selector:
    matchLabels:
      env: production
  replicas: 6
  template:
    metadata:
      name: nginx-2
      labels:
        # it seems like it doesn't have to match with the replicaset's labels
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
