apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otherapp-replicaset
  labels:
    app: otherapp
    type: front-end
spec:
  template:
    metadata:
      name: otherapp-pod
      labels: # this label doesn't have to be the same as the ReplicaSet's label!
        app: otherapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      type: front-end
