apiVersion: v1
kind: Pod
metadata:
  name: otherapp-pod
  labels:
    app: otherapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 8080
    # env:
    # - name: APP_COLOR
    #   value: pink
    # - name: APP_THEME
    #   valueFrom:
    #     configMapKeyRef: ConfigMap
    # - name: APP_SECRET
    #   valueFrom:
    #     secretKeyRef: Secret
    # resources:
    #   requests:
    #     memory: "1Gi"
    #     cpu: 1
    #   limits:
    #     memory: "2Gi"
    #     cpu: 2
  # nodeName: node01 # this is not necessary
  # tolerations to "kubectl taint nodes node1 app=blue:NoSchedule"
  # tolerations: # this is not necessary
  # - key: "app"
  #   operator: "Equal"
  #   value: "blue"
  #   effect: "NoSchedule"
  # nodeSelector:
  #   size: Large
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: size
  #           operator: In
  #           values:
  #           - Large
  #           - Medium
