apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.randomName }}
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 10
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
        commonLabel: common
    spec:
      containers:
      - name: app-container
        image: {{ .Values.image }}
  selectors:
    matchLabels:
      version: v1
      commonLabel: common