apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    app: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
    - secretKeyRef:
        name: otherapp-secret
    # env:
    # - name: DB_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: app-secret
    #       key: DB_PASSWORD
    # if we mount secret as a volume
    # volumes:
    # - name: otherapp-secret-volume
    #   secret:
    #     # because we have 2 secret keys in the secret file,
    #     # 2 files will be created.
    #     # The file's name is the key, the file's content is the value.
    #     secretName: otherapp-secret
